### ISSUE TITLE
Upload image doesn't get uploaded for books or shelves

### ISSUE THREAD

**Issue by brij-mandaliya** [Improwised/BookStack#33]
### Describe the feature you'd like

`https://github.com/BookStackApp/BookStack/issues/4275`

### Describe the benefits this would bring to existing BookStack users

- 

### Can the goal of this request already be achieved via other means?

- 

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Not using yet, just scoping

### Additional context

-

**Comment by brij-mandaliya** [comment]
There is no issue related to this,
bookstack working properly in BookStack: version 24.10.2

This is My Docker Compose File 
```
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack-linuxserver
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - APP_URL=http://localhost:6876
      - APP_KEY=bhjdkslairueydgshcbdgeudhbdjloyg
      - DB_HOST=
      - DB_PORT=3306
      - DB_USERNAME=bookstack-test
      - DB_PASSWORD=bookstack-test
      - DB_DATABASE=bookstack-dev
      - QUEUE_CONNECTION= #optional
    volumes:
      - ./BookStack/.env:/config/www/.env
      - ./BookStack/storage/logs/laravel.log:/config/log/bookstack/laravel.log
      - ./BookStack/storage/backups/:/config/backups/
      - ./BookStack/storage/uploads/files/:/config/www/files/
      - ./BookStack/storage/uploads/images/:/config/www/images/
      - ./BookStack/themes/:/config/www/themes/
      - ./BookStack/public/uploads/:/config/www/uploads/
    ports:
      - 6876:80
    restart: unless-stopped
    networks:
      - bookstack_default

networks:
  bookstack_default:
    external: true 
```

## Check the Path you provide for volume
